#!/bin/bash

action=$1

docker_compose_command="docker-compose -f testing/docker/docker-compose.yml --project-directory ."
case $action in
	test)
		set -o errexit
		set -o xtrace
		$docker_compose_command up -d
		docker exec raku_raku_1 /bin/bash -lc ./table-tests.rakutest
#		set +o xtrace
#		$docker_compose_command run raku ls -laF
#		$docker_compose_command down
		;;
	build)
		$docker_compose_command build raku
		;;
	stop)
		$docker_compose_command down
		;;
	build-docs)
		for sourcefile in `find lib \( -name '*.raku' -o -name '*.rakumod' \)`; do
			basename=`basename $sourcefile .rakumod`
			for out_type in Markdown HTML Text; do
				(set -x ; RAKULIB=lib/raku raku --doc=$out_type $sourcefile > docs/$out_type/${basename}.md)
			done
		done
		;;
	*)
		echo "Unknown action '$action'" >&2
		exit 1
		;;
esac
