version: "3.8"

services:
  # Docker for TOP
  raku:
    build:
      context: .
      dockerfile: docker/raku.dockerfile

  postgres:
    build:
      context: .
      dockerfile: docker/pagila.dockerfile
    environment:
      POSTGRES_DB: pagila
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
